server {
    listen 443 ssl;
    server_name calebnchloelove.org;

    ssl_certificate /etc/letsencrypt/live/calebnchloelove.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/calebnchloelove.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /.well-known/oauth-protected-resource {
        add_header Content-Type 'application/json';
        add_header Access-Control-Allow-Origin '*';
        return 200 '{"resource":"https://calebnchloelove.org/mcp/e9c9cc157695442bb47f35ecd3601e30/sse","authorization_servers":[]}';
    }

    location /.well-known/ {
        add_header Content-Type 'application/json';
        add_header Access-Control-Allow-Origin '*';
        return 200 '{}';
    }

    location /mcp/ {
        proxy_pass http://127.0.0.1:3456/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        chunked_transfer_encoding on;
    }
}

server {
    listen 80;
    server_name calebnchloelove.org;
    return 301 https://$host$request_uri;
}
